name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  rpottanat/shoppingapp:latest
    - name: Push the Docker image
      run:  run: docker login -u rpottanat -p ${{ secrets.DOCKER_TOKEN }} && docker push rpottanat/shoppingapp:latest
